max_timestep: 6000 #should be 6 times the color_change_timestep
agent_count: 100
neighbourhood_size: 5
color_count: 4
majority_color_ratio: 0.7
informed_ratio: 1.0
personal_info_weight: 0.0
sensor_noise: 0.0
communication_noise: 0.0
color_change_timestep: 1000
# was 40
total_simulation_runs: 20